# Generated by Django 5.2.4 on 2025-08-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_file', models.FileField(upload_to='templates/html/')),
                ('css_file', models.FileField(blank=True, null=True, upload_to='templates/css/')),
                ('js_file', models.FileField(blank=True, null=True, upload_to='templates/js/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
