# Generated by Django 5.2.4 on 2025-08-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_projecttemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttemplate',
            name='css_file',
        ),
        migrations.RemoveField(
            model_name='projecttemplate',
            name='html_file',
        ),
        migrations.RemoveField(
            model_name='projecttemplate',
            name='js_file',
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
