# Generated by Django 5.2.4 on 2025-08-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_projecttemplate_css_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='templates/icons/'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='template_type',
            field=models.CharField(choices=[('app', 'App'), ('website', 'Website')], default='website', max_length=10),
        ),
    ]
