# Generated by Django 5.2.4 on 2025-08-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_projecttemplate_icon_projecttemplate_template_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('service', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='service_docs/')),
                ('half_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
