# Generated by Django 5.2.4 on 2025-08-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('half_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
