# Generated by Django 5.2.4 on 2025-08-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_servicesubmission_delete_servicerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceSubmission',
        ),
    ]
